// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcyCvU2rke9YnRd8W7WAr1_qAEVCgp95Y',
    appId: '1:879353101921:web:f4736a96ec0d0464baf420',
    messagingSenderId: '879353101921',
    projectId: 'obaidah-654c4',
    authDomain: 'obaidah-654c4.firebaseapp.com',
    storageBucket: 'obaidah-654c4.appspot.com',
    measurementId: 'G-RWJ0QD32DX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRQ7yjYcGXJKGYOg6e5CCTG-Z6F4m2cb8',
    appId: '1:879353101921:android:d14aa3b5d115db35baf420',
    messagingSenderId: '879353101921',
    projectId: 'obaidah-654c4',
    storageBucket: 'obaidah-654c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0D1gy1YZ6Q9ir92ND2BspDOyEdv8-nPM',
    appId: '1:879353101921:ios:58ccb8ad13679ce5baf420',
    messagingSenderId: '879353101921',
    projectId: 'obaidah-654c4',
    storageBucket: 'obaidah-654c4.appspot.com',
    iosClientId: '879353101921-gn1il4rf1ok0dsccb1fvmc7h82iavqcr.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodDonationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0D1gy1YZ6Q9ir92ND2BspDOyEdv8-nPM',
    appId: '1:879353101921:ios:58ccb8ad13679ce5baf420',
    messagingSenderId: '879353101921',
    projectId: 'obaidah-654c4',
    storageBucket: 'obaidah-654c4.appspot.com',
    iosClientId: '879353101921-gn1il4rf1ok0dsccb1fvmc7h82iavqcr.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodDonationApp',
  );
}
